# Generated by Django 5.1.6 on 2025-03-02 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='created_at',
            new_name='createdOn',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='updated_at',
            new_name='updatedOn',
        ),
    ]
